"""CLI entry point: build every registered fixture and write corpus/.

Run with: uv run arcviz-fixtures [--corpus-dir PATH]
"""

import argparse
import sys
from pathlib import Path

from . import fixtures  # noqa: F401  (import registers every @fixture)
from .corpus_io import write_fixture
from .registry import FixtureBlocked, all_fixtures

DEFAULT_CORPUS_DIR = Path(__file__).resolve().parents[4] / "corpus"


def _topo_order(specs):
    by_name = {s.name: s for s in specs}
    order = []
    seen = set()
    visiting = set()

    def visit(name):
        if name in seen:
            return
        if name in visiting:
            raise RuntimeError(f"circular fixture dependency at {name!r}")
        visiting.add(name)
        for dep in by_name[name].depends_on:
            if dep not in by_name:
                raise RuntimeError(f"fixture {name!r} depends on unknown fixture {dep!r}")
            visit(dep)
        visiting.discard(name)
        seen.add(name)
        order.append(name)

    for s in specs:
        visit(s.name)
    return [by_name[n] for n in order]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus-dir", type=Path, default=DEFAULT_CORPUS_DIR)
    args = parser.parse_args(argv)

    corpus_dir = args.corpus_dir
    corpus_dir.mkdir(parents=True, exist_ok=True)

    specs = _topo_order(all_fixtures())

    ok, blocked, failed = [], [], []

    for spec in specs:
        print(f"[{spec.name}] generating...", file=sys.stderr)
        try:
            result = spec.fn(corpus_dir)
        except FixtureBlocked as exc:
            blocked.append((spec.name, str(exc)))
            print(f"[{spec.name}] BLOCKED: {exc}", file=sys.stderr)
            continue
        except Exception as exc:  # noqa: BLE001 -- report, don't crash the whole run
            failed.append((spec.name, repr(exc)))
            print(f"[{spec.name}] FAILED: {exc!r}", file=sys.stderr)
            continue

        serder = result["serder"]
        meta = dict(result["meta"])
        meta["name"] = spec.name
        if spec.depends_on:
            meta.setdefault("depends_on", spec.depends_on)
        write_fixture(corpus_dir, spec.name, sad=serder.sad, meta=meta,
                      raw=bytes(serder.raw), expanded=result.get("expanded"))

        for extra_name, extra_serder in result.get("extra_writes", {}).items():
            write_fixture(
                corpus_dir, extra_name, sad=extra_serder.sad,
                meta={
                    "name": extra_name,
                    "title": f"Registry inception ('rip') for {spec.name}",
                    "summary": f"The registry {spec.name}'s `rd` field points at (via its SAID).",
                    "matrix_cells": [],
                    "rules_exercised": [],
                    "parent_fixture": spec.name,
                },
                raw=bytes(extra_serder.raw),
            )

        ok.append(spec.name)
        print(f"[{spec.name}] OK -> {spec.name}.json (said={serder.said})", file=sys.stderr)

    _write_corpus_readme(corpus_dir, ok, blocked, failed)

    print(f"\n{len(ok)} generated, {len(blocked)} blocked, {len(failed)} failed.",
          file=sys.stderr)
    for name, reason in blocked:
        print(f"  BLOCKED {name}: {reason}", file=sys.stderr)
    for name, reason in failed:
        print(f"  FAILED  {name}: {reason}", file=sys.stderr)

    return 1 if failed else 0


def _write_corpus_readme(corpus_dir: Path, ok, blocked, failed):
    import json

    lines = [
        "# arcviz ACDC fixture corpus",
        "",
        "Generated by `tools/fixtures` (see that directory's README.md for how "
        "and why). Every fixture below is a real, self-SAIDed ACDC (or "
        "registry-inception message) computed via keripy "
        "(`~/code/wot/keripy`) -- SAIDs recompute, they are not hand-edited.",
        "",
        "Each `<name>.json` is the disclosed field map (what a renderer would "
        "receive); `<name>.cesr` is the identical content as the exact wire-"
        "serialized bytes; `<name>.meta.json` names which disclosure-matrix "
        "cell/rule the fixture exercises; a `<name>.expanded.json`, where "
        "present, is a reference-only file showing content a real presenter "
        "using that fixture's mechanism would NOT disclose (kept for test "
        "verification, never itself \"the fixture\").",
        "",
        "## Fixtures",
        "",
        "| Fixture | Title | Matrix cells | Rules | Depends on |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(ok):
        meta_path = corpus_dir / f"{name}.meta.json"
        if not meta_path.exists():
            continue
        meta = json.loads(meta_path.read_text())
        cells = ", ".join(meta.get("matrix_cells", [])) or "—"
        rules = ", ".join(meta.get("rules_exercised", [])) or "—"
        deps = ", ".join(meta.get("depends_on", [])) or "—"
        lines.append(f"| `{name}` | {meta.get('title', '')} | {cells} | {rules} | {deps} |")

    registry_metas = sorted(corpus_dir.glob("*.registry.meta.json"))
    if registry_metas:
        lines += [
            "",
            "## Registries",
            "",
            "Registry-inception (`rip`) messages, one per vLEI-equivalent-chain "
            "credential's `rd` field (see corpus-vlei-chain.md sec.3: \"four "
            "registries\"). Not full TEL simulation -- see fx_vlei.py's module "
            "docstring for what's out of scope.",
            "",
            "| Registry | For fixture |",
            "|---|---|",
        ]
        for meta_path in registry_metas:
            meta = json.loads(meta_path.read_text())
            reg_name = meta_path.name.removesuffix(".meta.json")
            lines.append(f"| `{reg_name}` | `{meta.get('parent_fixture', '')}` |")

    if blocked:
        lines += ["", "## Targeted but not generated", ""]
        for name, reason in blocked:
            lines.append(f"- **{name}**: {reason}")

    if failed:
        lines += ["", "## Generation errors (bugs, not honest blockers)", ""]
        for name, reason in failed:
            lines.append(f"- **{name}**: {reason}")

    lines += [
        "",
        "## Known limitations",
        "",
        "- No KEL/TEL event simulation (no `icp`/`dip`/`drt`/`ixn`, no signing, "
        "no witnesses). Every AID here is a deterministic blake3-digest "
        "placeholder, not one anchored in any inception event. See "
        "`tools/fixtures/README.md` \"What this does not model\" and "
        "`fx_vlei.py`'s module docstring for exactly which corpus-vlei-chain.md "
        "facts (weighted multisig, the one asymmetric key rotation, the "
        "absent root delegator's KEL) this does NOT reproduce.",
        "- `working_edge_group` is generated directly via `acdcmap` + "
        "`Compactor`, not round-tripped through keripy's own "
        "`Reger.sources`/`Verifier.processCredential`, which is documented as "
        "unable to traverse edge-groups at all. Its SAIDs and structure are "
        "real and correct; it has not been proven to survive keripy's own "
        "verifier.",
        "- No separate generic \"depth-3-or-more chain\" fixture: the "
        "`vlei_qvi -> vlei_le -> vlei_ecr_auth -> vlei_ecr` chain (depth 4) "
        "satisfies that corpus-keripy-examples.md gap already.",
        "- Edge (`e`) and Rule (`r`) sections are schema-typed loosely "
        "(`oneOf` [string, object], no nested property schema) rather than "
        "elaborated to the ACDC spec's own worked-example fidelity. See "
        "`tools/fixtures/src/arcviz_fixtures/schemas.py`'s module docstring.",
    ]

    (corpus_dir / "README.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
